name: Deploy to Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Front-end build (optional) ---
      # If your template needs a JS build, uncomment:
      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      # - name: Install JS deps
      #   run: npm ci
      # - name: Build assets
      #   run: npm run build

      - name: Rsync code to server
        uses: burnett01/rsync-deployments@7.0
        with:
          switches: -avz --delete \
            --exclude='.git*' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='venv' \
            --exclude='.venv' \
            --exclude='__pycache__' \
            --exclude='.env' \
            --exclude='db.sqlite3' \
            --exclude='media' \
            --exclude='staticfiles'
          path: ./
          remote_path: /home/dncouncil/apps/mydjango/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Run deploy script on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            /home/dncouncil/apps/mydjango/deploy.sh
